### ISSUE TITLE
Visible Keys

### ISSUE THREAD

**Issue by kayelow** [orangies/got7schebot#1]
Hi, didn't see an email or other contact! Just came across your repo this morning and noticed you have your keys public
https://github.com/orangies/got7schebot/blob/master/secret.json

Suggesting that you add that file to your `.gitignore` and rotate your keys. 

<3 fellow ahagase

**Comment by orangies** [comment]
Thanks for telling me. I'm very new about github. Very glad we have ahgase here :)
